openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: 'AWS App Runner Amazon App Runner AWS App Runner API #X Amz Target=AppRunner.ListOperations #X Amz Target=AppRunner.ListOperations #X Amz Target=AppRunner.ListOperations API'
  description: <fullname>App Runner</fullname> <p>App Runner is an application service that provides a fast, simple, and cost-effective way to go directly from an existing container image or source code to a running service in the Amazon Web Services Cloud in seconds. You don't need to learn new technologies, decide which compute service to use, or understand how to provision and configure Amazon Web Services resources.</p> <p>App Runner connects directly to your container registry or source code repository. It provides an automatic delivery pipeline with fully managed operations, high performance, scalability, and security.</p> <p>For more information about App Runner, see the <a href="https://docs.aws.amazon.com/apprunner/latest/dg/">App Runner Developer Guide</a>. For release information, see the <a href="https://docs.aws.amazon.com/apprunner/latest/relnotes/">App Runner Release Notes</a>.</p> <p> To install the Software Development Kits (SDKs), Integrated Development Environment (IDE) Toolkits, and command line tools that you can use to access the API, see <a href="http://aws.amazon.com/tools/">Tools for Amazon Web Services</a>.</p> <p> <b>Endpoints</b> </p> <p>For a list of Region-specific endpoints that App Runner supports, see <a href="https://docs.aws.amazon.com/general/latest/gr/apprunner.html">App Runner endpoints and quotas</a> in the <i>Amazon Web Services General Reference</i>.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apprunner
  x-aws-signingName: apprunner
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apprunner-2020-05-15.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: https://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: http://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
- url: https://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AppRunner.ListOperations'
paths:
  /#X-Amz-Target=AppRunner.ListOperations:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListOperations
      description: <p>Return a list of operations that occurred on an App Runner service.</p> <p>The resulting list of <a>OperationSummary</a> objects is sorted in reverse chronological order. The first object on the list represents the last started operation.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOperationsResponse'
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '481':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListOperationsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AppRunner.ListOperations
      tags:
      - '#X Amz Target=AppRunner.ListOperations'
components:
  schemas:
    InternalServiceErrorException: {}
    ListOperationsRequest:
      type: object
      required:
      - ServiceArn
      title: ListOperationsRequest
      properties:
        ServiceArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: The Amazon Resource Name (ARN) of the App Runner service that you want a list of operations for.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: <p>A token from a previous result page. It's used for a paginated request. The request retrieves the next result page. All other parameter values must be identical to the ones specified in the initial request.</p> <p>If you don't specify <code>NextToken</code>, the request retrieves the first result page.</p>
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/ListOperationsMaxResults'
          - description: <p>The maximum number of results to include in each response (result page). It's used for a paginated request.</p> <p>If you don't specify <code>MaxResults</code>, the request retrieves all available results in a single response.</p>
    ResourceNotFoundException: {}
    OperationSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/OperationSummary'
    ListOperationsResponse:
      type: object
      properties:
        OperationSummaryList:
          allOf:
          - $ref: '#/components/schemas/OperationSummaryList'
          - description: A list of operation summary information records. In a paginated request, the request returns up to <code>MaxResults</code> records for each call.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The token that you can pass in a subsequent request to get the next result page. It's returned in a paginated request.
    UUID:
      type: string
      pattern: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}'
      minLength: 36
      maxLength: 36
    AppRunnerResourceArn:
      type: string
      pattern: arn:aws(-[\w]+)*:[a-z0-9-\\.]{0,63}:[a-z0-9-\\.]{0,63}:[0-9]{12}:(\w|\/|-){1,1011}
      minLength: 1
      maxLength: 1011
    Timestamp:
      type: string
      format: date-time
    ListOperationsMaxResults:
      type: integer
      minimum: 1
      maximum: 20
    OperationType:
      type: string
      enum:
      - START_DEPLOYMENT
      - CREATE_SERVICE
      - PAUSE_SERVICE
      - RESUME_SERVICE
      - DELETE_SERVICE
      - UPDATE_SERVICE
    OperationSummary:
      type: object
      properties:
        Id:
          allOf:
          - $ref: '#/components/schemas/UUID'
          - description: A unique ID of this operation. It's unique in the scope of the App Runner service.
        Type:
          allOf:
          - $ref: '#/components/schemas/OperationType'
          - description: The type of operation. It indicates a specific action that occured.
        Status:
          allOf:
          - $ref: '#/components/schemas/OperationStatus'
          - description: The current state of the operation.
        TargetArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: The Amazon Resource Name (ARN) of the resource that the operation acted on (for example, an App Runner service).
        StartedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the operation started. It's in the Unix time stamp format.
        EndedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the operation ended. It's in the Unix time stamp format.
        UpdatedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the operation was last updated. It's in the Unix time stamp format.
      description: Provides summary information for an operation that occurred on an App Runner service.
    InvalidRequestException: {}
    OperationStatus:
      type: string
      enum:
      - PENDING
      - IN_PROGRESS
      - FAILED
      - SUCCEEDED
      - ROLLBACK_IN_PROGRESS
      - ROLLBACK_FAILED
      - ROLLBACK_SUCCEEDED
    String:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 51200
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apprunner/
x-hasEquivalentPaths: true
